services:
  proton:
    image: d.timeplus.com/timeplus-io/proton:latest
    pull_policy: always
    ports:
      - 8463:8463
      - 3218:3218

  carsharing_datagen:
    image: docker.timeplus.com/timeplus/cardemo:latest
    entrypoint: /bin/sh
    command: -c "sleep 15 && echo \"$$CONSOLE_CONFIG_FILE\" > /timeplus/sink.yaml;  /timeplus/cardemo --config /timeplus/.cardemo.yaml -f /timeplus/sink.yaml"
    environment:
      CONSOLE_CONFIG_FILE: |
        sinks:
          - type: proton
            properties:
              interval: 200
              host: proton
    depends_on:
      - proton

  grafana:
    image: grafana/grafana:latest
    pull_policy: always
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: timeplus-proton-datasource
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning
    depends_on:
      - proton
