services:
  proton:
     image: ghcr.io/timeplus-io/proton:latest
     pull_policy: always
     ports:
       - 3218:3218 #http port for JDBC driver, default streaming mode
       - 8123:8123 #http port for JDBC driver, default batch mode
       - 8463:8463 #tcp port for go driver or grafana plugin
     healthcheck:
        test: ["CMD", "curl", "http://localhost:3218/proton/ping"]
        interval: 2s
        timeout: 10s
        retries: 3
        start_period: 10s

  init-proton:
    image: ghcr.io/timeplus-io/proton:latest
    command:
      - sh
      - -c
      - |
        proton-client -h proton -n --query "CREATE STREAM IF NOT EXISTS phone(raw string)"
    depends_on:
      proton:
        condition: service_healthy         

  proxy:
    image: timeplus/sensor-logger-proxy
    ports:
       - 8000:3000 #expose internal port 3000 as 8000, avoiding conflicts with Grafana. This will forward HTTP POST to proton:3218
    environment:
      HOST: proton
      STREAM: phone
    depends_on:
      - proton

  grafana:
    image: grafana/grafana:latest
    pull_policy: always
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: timeplus-proton-datasource
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning
    depends_on:
      init-proton:
        condition: service_completed_successfully