name: Bet you know

on:
  schedule:
    - cron: '0 2 * * 1-5' # Workflow runs at 10:00 AM Beijing time on weekdays

  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    - name: Create build directory
      run: cd $GITHUB_WORKSPACE && mkdir build && pwd && cd build &&
           brew install ccache cmake ninja libtool gettext llvm@16 gcc binutils grep findutils libiconv &&
           export CC=$(brew --prefix llvm@16)/bin/clang && 
           export CXX=$(brew --prefix llvm@16)/bin/clang++ && 
           export PATH=$(brew --prefix llvm@16)/bin:$PATH && cmake .. && ninja
