name: Bet you know

on:
  schedule:
    - cron: '0 2 * * 1-5' # Workflow runs at 10:00 AM Beijing time on weekdays

  workflow_dispatch: # Manual trigger

env:
  build_directory: ${{ github.workspace }}/build
  build_type: Release
  release_name: proton

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch_depth: 1
          submodules: true

      - name: Install dependencies
        run: |
          brew install ccache cmake ninja libtool gettext llvm@16 gcc binutils grep findutils libiconv

      - name: new version cut
        run: |
          git config --local name "jul11"
          git config --local email "haohang.shi@timeplus.io"
          ./release version --patch

      - name: Create build directory
        run: mkdir -p ${{ env.build_directory }}

      - name: Configure CMake
        run: |
          export CC=$(brew --prefix llvm@16)/bin/clang
          export CXX=$(brew --prefix llvm@16)/bin/clang++
          export PATH=$(brew --prefix llvm@16)/bin:$PATH
          cmake -B ${{ env.build_directory }} -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.build_type }}

      - name: Build with Ninja
        run: cmake --build ${{ env.build_directory }}

      - name: Strip binary
        run: |
          ls -lh ${{ env.build_directory }}/programs/proton
          /opt/homebrew/opt/llvm@16/bin/llvm-strip ${{ env.build_directory }}/programs/proton
          ls -lh ${{ env.build_directory }}/programs/proton

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.release_name }}
      #     path: ${{ env.build_directory }}/programs/proton

      # - name: Create Release
      #   run: gh release create v1.0 ${{ env.build_directory }}/programs/proton
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  # release:
  #   needs: build
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Download Artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: ${{ env.release_name }}

  #     - name: Create Release
  #       run: gh release create v1.0 ${{ env.build_directory }}/programs/proton
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
